core/urls.py
from django.urls import path

from .views import (
    ItemListView,
    CheckoutView, 
    HomeListView, 
    ItemDetailView,
    OrderSummaryView,
    add_to_cart,
    remove_from_cart,
    remove_single_item_from_cart,
    PaymentView,
    AddCouponView,
    RequestRefundView,
    )
app_name = 'core'

urlpatterns = [
    path('', HomeListView.as_view(), name='home'),
    path('category-search/<category_name>', HomeListView.as_view(), 
    name='category-search'),
    path('item_list/', ItemListView.as_view(), name='items'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('product_detail/<slug>', ItemDetailView.as_view(), name='product'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('add-coupon/', AddCouponView.as_view(), name='add-coupon'),
    path('remove-single-item-from-cart/<slug>/', remove_single_item_from_cart, 
    name='remove-single-item-from-cart'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),
    path('request-refund/', RequestRefundView.as_view(), name='request-refund'),
]

core/models.py
from django.conf import settings
from django.db import models
from django.db.models import Q
from django.shortcuts import reverse
from django.db.models.signals import pre_save, pre_delete
from django.dispatch.dispatcher import receiver
from .utils import unique_slug_generator

User = settings.AUTH_USER_MODEL

CATEGORY_CHOICES = (
    ('S', 'Shirt'),
    ('SW', 'Sport Wear'),
    ('OW', 'Outwear'),
    ('P', 'Pants'),
    ('O', 'Other'),
)
LABEL_CHOICES = (
    ('P', 'primary'),
    ('S', 'secondary'),
    ('D', 'danser'),
)
ADDRESS_CHOICES = (
    ('B', 'Billing'),
    ('S', 'Shipping'),
)

class ItemQuerySet(models.query.QuerySet):
    def search(self, query):
        if query:
            query = query.strip()
            return self.filter(
                Q(title__icontains=query) |
                Q(description__icontains=query) |
                Q(category__icontains=query)
                ).distinct()
        return self

class ItemManager(models.Manager):
    def get_queryset(self):
        return ItemQuerySet(self.model, using=self._db)

    def search(self, query):
        return self.get_queryset().search(query)

class Item(models.Model):
    title               = models.CharField(max_length=100)
    price               = models.FloatField()
    discount_price      = models.FloatField(blank=True, null=True)
    category            = models.CharField(choices=CATEGORY_CHOICES, max_length=2)
    label               = models.CharField(choices=LABEL_CHOICES, max_length=1)
    slug                = models.SlugField(blank=True, null=True)
    description         = models.TextField()
    quantity            = models.IntegerField(default=1)
    image               = models.ImageField(upload_to='products/', 
                          null=True, 
                          blank=True)

    objects             = ItemManager()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("core:product", kwargs={"slug": self.slug})

    def get_add_to_cart_url(self):
        return reverse("core:add-to-cart", kwargs={"slug": self.slug})

    def get_remove_from_cart_url(self):
        return reverse("core:remove-from-cart", kwargs={"slug": self.slug})


class ItemImage(models.Model):
    item    = models.ForeignKey(Item, related_name="images", on_delete=models.CASCADE)
    image   = models.ImageField(upload_to='products/', blank=True, null=True)

    def __str__(self):
        return self.item.title


class OrderItem(models.Model):
    user        = models.ForeignKey(User, on_delete=models.CASCADE)
    ordered     = models.BooleanField(default=False)
    item        = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity    = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} of {self.item.title}"

    def get_total_item_price(self):
        return self.item.price * self.quantity

    def get_total_discount_item_price(self):
        discount_price = self.item.discount_price
        if discount_price and discount_price > 0:
            return discount_price * self.quantity
        else:
            return 0

    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_total_discount_item_price()

    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_discount_item_price()
        return self.get_total_item_price()


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    ref_code = models.CharField(max_length=20, blank=True, null=True)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    order_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)
    billing_address = models.ForeignKey('Address',
        related_name = 'billing_address',
        on_delete=models.SET_NULL, 
        blank=True, 
        null=True,
        )
    shipping_address = models.ForeignKey('Address',
        related_name = 'shipping_address',
        on_delete=models.SET_NULL, 
        blank=True, 
        null=True,
        )
    payment = models.ForeignKey('Payment',
        on_delete=models.SET_NULL, 
        blank=True, 
        null=True
        )
    coupon = models.ForeignKey('Coupon',
        on_delete=models.SET_NULL, 
        blank=True, 
        null=True
        )
    being_delivered = models.BooleanField(default=False)
    received = models.BooleanField(default=False)
    refund_requested = models.BooleanField(default=False)
    refund_granted = models.BooleanField(default=False)

    def __str__(self):
        return str(self.start_date)

    def get_total(self):
        total = 0
        for oi in self.items.all():
            total += oi.get_final_price()
        if self.coupon:
            total -= self.coupon.amount
        return total


class Address(models.Model):
    user                  = models.ForeignKey(User, 
                            blank=True, 
                            null=True,
                            on_delete=models.SET_NULL)
    street_address        = models.CharField(max_length=100)
    apartment_address     = models.CharField(max_length=100)
    country               = models.CharField(max_length=100)
    zip                   = models.CharField(max_length=100)
    address_type          = models.CharField(max_length=2, choices=ADDRESS_CHOICES)
    default               = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username


class Payment(models.Model):
    stripe_charge_id = models.CharField(max_length=50)
    user = models.ForeignKey(User, 
        on_delete=models.SET_NULL, 
        blank=True,
        null=True
        )
    amount = models.FloatField()
    timestamp = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        if self.user:
            return "User: " + self.user.username + " Amount: " + str(self.amount)
        else:
            return "User: Deleted User. Amount: " + str(self.amount)


class Coupon(models.Model):
    code    = models.CharField(max_length=15)
    amount  = models.FloatField()

    def __str__(self):
        return self.code


class Refund(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    reason = models.TextField()
    accepted = models.BooleanField(default=False)
    email = models.EmailField()
    def __str__(self):
        return f"{self.pk}"
    
def item_pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance=instance)

@receiver(pre_delete, sender=Item)
@receiver(pre_delete, sender=ItemImage)
def image_delete_handler(sender, instance, *args, **kwargs):
    if instance.image and instance.image.url:
        instance.image.delete()

pre_save.connect(item_pre_save_receiver, sender=Item)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>{% block title %} DJCom {% endblock %}</title>
  {% block extra_head %}
  {% endblock %}
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
  <!-- Bootstrap core CSS -->
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <!-- Material Design Bootstrap -->
  <link href={% static 'css/mdb.min.css' %} rel="stylesheet">
  <!-- Your custom styles (optional) -->
  <link href={% static 'css/style.min.css'%} rel="stylesheet">
  <style type="text/css">
    html,
    body,
    header,
    .carousel {
      height: 60vh;
    }

    @media (max-width: 740px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

    @media (min-width: 800px) and (max-width: 850px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

  </style>
</head>

{% include 'main_nav.html'%}

<body>
<div class='mt-5 pt-4'>
  {% if messages %}
      {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      {% endfor %}
  {% endif %}
</div>

{% block content %}{% endblock content %}

{% block extra_body %}{% endblock extra_body %}

{% include 'main_footer.html' %}
{% include 'scripts.html' %}

{% block extra_scripts %}
{% endblock extra_scripts %}
</body>
</html>

templates/category_nav.html
<main>
    <div class="container">
        <!--Navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5">
            <!-- Navbar brand -->
            <span class="navbar-brand">Categories:</span>
            <!-- Collapse button -->
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
                aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <!-- Collapsible content -->
            <div class="collapse navbar-collapse" id="basicExampleNav">
                <!-- Links -->
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'core:home' %}">All
                        <span class="sr-only">(current)</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href={% url 'core:category-search' category_name='Shirt'%}>Shirts</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Sport wears</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Outwears</a>
                    </li>
                </ul>
                <!-- Links -->
                <form class="form-inline" method='GET' action=''>
                {% csrf_token %}
                    <div class="md-form my-0">
                        <input class="form-control mr-sm-2" type="text" 
                        placeholder="Search..." aria-label="Search"
                        name='query' value={{ request.GET.query}}>
                        <button class='btn btn-default bg-dark text-light' type='submit'>Search</button>
                    </div>
                </form>
            </div>
            <!-- Collapsible content -->
        </nav>
        <!--/.Navbar-->
    </div>
</main>

templates/item_list.html
{% extends 'base.html' %}

{% block content %}

{% comment %} {% include 'slides.html' %} {% endcomment %}
{% include 'category_nav.html' %}

<main>
    <div class="container">

      <!--Section: Products v.3-->
      <section class="text-center mb-4">

        <!--Grid row-->
        <div class="row wow fadeIn">
            {% for product in object_list %}
                <!--Grid column-->
                <div class="col-lg-3 col-md-6 mb-4">

                    <!--Card-->
                    <div class="card">

                    <!--Card image-->
                    <div class="view overlay">
                        {% if product.image %}
                        <img src="{{ product.image.url }}" class="card-img-top">
                        {% endif %}
                        <a href="{{ product.get_absolute_url }}">
                        <div class="mask rgba-white-slight"></div>
                        </a>
                    </div>
                    <!--Card image-->

                    <!--Card content-->
                    <div class="card-body text-center">
                        <!--Category & Title-->
                        <a href="" class="grey-text">
                        <h5>{{ product.get_category_display }}</h5>
                        </a>
                        <h5>
                        <strong>
                            <a href="{{ product.get_absolute_url }}" class="dark-grey-text">{{ product.title }}
                            <span class="badge badge-pill {{ product.get_label_display }}-color">NEW</span>
                            </a>
                        </strong>
                        </h5>

                        <h4 class="font-weight-bold blue-text">
                        <strong>
                            {% if product.discount_price %}
                                <span>{{ product.discount_price }}</span>
                            {% else %}
                                <span>{{ product.price }}</span>
                            {% endif %}              
                        </strong>
                        </h4>
                    </div>
                    <!--Card content-->
                    </div>
                    <!--Card-->
                </div>
                <!--Grid column-->
            {% endfor %}
        </div>
        <!--Grid row-->
      </section>
      <!--Section: Products v.3-->
      {% if is_paginated %}
        <!--Pagination-->
        <nav class="d-flex justify-content-center wow fadeIn">
          <ul class="pagination pg-blue">
          {% if page_obj.has_previous %}
            <!--Arrow left-->
            <li class="page-item">
              <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
                <span class="sr-only">Previous</span>
              </a>
            </li>
          {% endif %}
            <li class="page-item active">
              <a class="page-link" href="?page={{ page_obj.number }}">{{ page_obj.number }}
                <span class="sr-only">(current)</span>
              </a>
            </li>
            {% if page_obj.has_next %}
              <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                  <span aria-hidden="true">&raquo;</span>
                  <span class="sr-only">Next</span>
                </a>
              </li>
            {% endif %}
          </ul>
        </nav>
        <!--Pagination-->
      {% endif %}
    </div
</main>
  <!--Main layout-->

{% endblock content %}

templates/main_footer.html
{% load static %}

  <!--Footer-->
  <footer class="page-footer text-center font-small mt-4 wow fadeIn">

    <hr class="my-4">

    <!-- Social icons -->
    <div class="pb-4">
      <a href="">
        <i class="fab fa-facebook-f mr-3"></i>
      </a>

      <a href="">
        <i class="fab fa-twitter mr-3"></i>
      </a>

      <a href="">
        <i class="fab fa-youtube mr-3"></i>
      </a>

      <a href="">
        <i class="fab fa-google-plus-g mr-3"></i>
      </a>

      <a href="">
        <i class="fab fa-dribbble mr-3"></i>
      </a>

      <a href="">
        <i class="fab fa-pinterest mr-3"></i>
      </a>

      <a href="">
        <i class="fab fa-github mr-3"></i>
      </a>

      <a href="">
        <i class="fab fa-codepen mr-3"></i>
      </a>
    </div>
    <!-- Social icons -->

    <!--Copyright-->
    <div class="footer-copyright py-3">
      © 2019 Copyright:
      <a href=""> MDBootstrap.com </a>
    </div>
    <!--/.Copyright-->

  </footer>
  <!--/.Footer-->

  <!-- SCRIPTS -->
  <!-- JQuery -->
  {% comment %} <script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
  <!-- Bootstrap tooltips -->
  <script type="text/javascript" src="{% static 'js/popper.min.js'%}"></script>
  <!-- Bootstrap core JavaScript -->
  <script type="text/javascript" src="{% static 'js/bootstrap.min.js'%}"></script>
  <!-- MDB core JavaScript -->
  <script type="text/javascript" src="{% static 'js/mdb.min.js'%}"></script>
  <!-- Initializations -->
  <script type="text/javascript">
    // Animations initialization
    new WOW().init();
  </script> {% endcomment %}

templates/order_snippet.html
<div class="col-md-12 mb-4">
    <h4 class="d-flex justify-content-between align-items-center mb-3">
    <span class="text-muted">Your cart</span>
    <span class="badge badge-secondary badge-pill">{{ order.items.count }}</span>
    </h4>
    <ul class="list-group mb-3 z-depth-1">
        {% for order_item in order.items.all %}
        <li class="list-group-item d-flex justify-content-between lh-condensed">
            <div>
            {{ order_item.quantity }} x 
            <a href={{ order_item.item.get_absolute_url }}>
                {{ order_item.item.title}}
            </a>
            {% comment %} <small class="text-muted">{{ order_item.item.description}}</small> {% endcomment %}
            </div>
            <span class="text-muted">DKK {{ order_item.get_final_price }}</span>
        </li>
        {% endfor %}
        {% if order.coupon %}
        <li class="list-group-item d-flex justify-content-between bg-light">
            <div class="text-success">
            <h6 class="my-0">Promo code</h6>
            <small>{{ order.coupon.code }}</small>
            </div>
            <span class="text-success">-DKK {{ order.coupon.amount }}</span>
        </li>
        {% endif %}
        <li class="list-group-item d-flex justify-content-between">
            <span>Total (DKK)</span>
            <strong>DKK {{ order.get_total }}</strong>
        </li>
    </ul>

    {% if DISPLAY_COUPON_FORM %}
        <form class="card p-2" action="{% url 'core:add-coupon' %}" method="POST">
            {% csrf_token %}
            <div class="input-group">
                {{ couponform.code }}
                <div class="input-group-append">
                <button class="btn btn-secondary btn-md waves-effect m-0" type="submit">Redeem</button>
                </div>
            </div>
        </form>
    {% endif %}

</div>

templates/order_summary.html
{% extends 'base.html' %}

{% block title %} Cart | {{ block.super }} {% endblock title %}  
{% block content %}
  <!--Main layout-->
  <main>
    <div class="container">

      <!--Grid row-->
      <div class="row wow fadeIn">
        <!--Grid column-->
        <div class="col-6 offset-3">
                
            <h2>Order Summary</h2>
            <table class="table table-sm">
                <thead>
                    <tr>
                    <th scope="col">#</th>
                    <th scope="col">Title</th>
                    <th scope="col">Price</th>
                    <th scope="col">Quantity</th>
                    <th scope="col">Total Item Price</th>
                    </tr>
                </thead>
                <tbody>
                    {% for order_item in order_object.items.all %}
                        <tr>
                        <th scope="row">{{forloop.counter}}</th>
                        <td>{{order_item.item.title}}</td>
                        <td>{{order_item.item.price}}</td>
                        <td>                
                          <a href="{% url 'core:remove-single-item-from-cart' order_item.item.slug %}"><i class="fas fa-minus mr-2"></i></a>
                          {{ order_item.quantity }}
                          <a href="{% url 'core:add-to-cart' order_item.item.slug %}"><i class="fas fa-plus ml-2"></i></a>
                        </td>
                        <td>
                          {% if order_item.item.discount_price %}
                              DKK {{ order_item.get_total_discount_item_price }}
                              <span class="badge badge-primary"> Saving DKK {{ order_item.get_amount_saved }}</span>
                          {% else %}
                              DKK {{ order_item.get_total_item_price }}
                          {% endif %}
                              <a style='color: red;' href="{% url 'core:remove-from-cart' order_item.item.slug %}">
                              <i class="fas fa-trash float-right"></i>
                          </a>
                        </td>
                        </tr>
                        {% empty %}
                        <tr>
                          <td>Your cart is empty</td>
                        </tr>
                        <tr>
                          <td colspan='5'>
                          <a class='btn btn-primary float-right' href='/'>Continue Shopping</b>
                        </tr>
                    {% endfor %}
                    {% if order_object.coupon %}
                     <tr>
                        <td  colspan="4"><b>Coupon</b></td>
                        <td><b>-{{ order_object.coupon.amount }}</b></td>
                      </tr> 
                    {% endif %}
                    {% if order_object.get_total %}
                      <tr>
                        <td  colspan="4"><b>Order Total</b></td>
                        <td><b>{{ order_object.get_total }}</b></td>
                      </tr>
                      <tr>
                        <td colspan='5'>
                        <a class='btn btn-warning float-right ml-2' href='/checkout/'>Proceed to Checkout</a>
                        <a class='btn btn-primary float-right' href='/'>Continue Shopping</a>
                      </tr>
                    {% endif %}
                </tbody>
            </table>
        </div>
        <!--Grid column-->
      </div>
      <!--Grid row-->
    </div>
  </main>
  <!--Main layout-->

{% endblock content %}

templates/product_detail.html
{% extends 'base.html' %}

{% block title %} {{ object.title.capitalize }} | {{ block.super }} {% endblock title %}  
{% block content %}
  <main class="mt-5 pt-4">
    <div class="container dark-grey-text mt-5">
      <div class="row wow fadeIn" >
        <div class="col-md-1 mb-1">
          {% for image in images %}
            <img src={{ image.image.url }} id='image_thumb' 
            value={{image.image.url}} class="img-fluid" alt=""
            onclick='displayAsMainImage(this)'>
          {% endfor %}
        </div>
        <div class="col-md-4 mb-3">
          {% if object.image and object.image.url %}
            <img src={{ object.image.url }} id='main_image' class="img-fluid" alt="">
          {% endif %}
        </div>
        <div class="col-md-6 mb-4">
          <div class="p-4">
            <div class="mb-3">
              <a href="">
                <span class="badge purple mr-1">{{ object.get_category_display}}</span>
              </a>
            </div>
            <p class="lead">
              {% if object.discount_price %}
              <span class="mr-1">
                <del>{{ object.price }}</del>
              </span>
              <span class="mr-1">
                <span>{{ object.discount_price }}</span>
              </span>
              {% else %}
                <span>{{ object.price }}</span>
              {% endif %}              
            </p>
            <p class="lead font-weight-bold">Description</p>
            <p>{{ object.description }}</p>
            <a href={{ object.get_add_to_cart_url }}
                class="btn btn-primary btn-md my-0 p">
                Add to cart
                <i class="fas fa-shopping-cart ml-1"></i>
            </a>
            <a href={{ object.get_remove_from_cart_url }}
                class="btn btn-danger btn-md my-0 p">
                Remove from cart
            </a>
          </div>
        </div>
      </div>
      <hr>
      <div class="row d-flex justify-content-center wow fadeIn">
        <div class="col-md-6 text-center">
          <h4 class="my-4 h4">Additional information</h4>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus suscipit modi sapiente illo soluta odit
            voluptates,
            quibusdam officia. Neque quibusdam quas a quis porro? Molestias illo neque eum in laborum.</p>
        </div>
      </div>
      <div class="row wow fadeIn">
        {% comment %} <div class="col-lg-4 col-md-12 mb-4">
          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/11.jpg" class="img-fluid" alt=""> 
        </div>
        <div class="col-lg-4 col-md-6 mb-4">
          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/12.jpg" class="img-fluid" alt="">
        </div> {% endcomment %}
          {% comment %} <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/13.jpg" class="img-fluid" alt=""> {% endcomment %}
          {% for image in images %}
          <div class="col-lg-4 col-md-6 mb-4">
            <img src={{ image.image.url }} class="img-fluid" alt="">
          </div>
          {% endfor %}
      </div>
    </div>
  </main>
{% endblock content %}
{% block extra_scripts %}
<script>
function displayAsMainImage(image){
  var main_image = document.getElementById('main_image');
  main_image.src = image.src;
}
</script>
{% endblock extra_scripts %}

templates/request_refund_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %} Refund | {{ block.super }} {% endblock title %}  

{% block content %}
  <main>
    <div class="container">
        <h2>Request Refund</h2>
        <form method="POST" action='.'>
            {% csrf_token %}
            {{ form|crispy }}
            <button type='submit' class='btn btn-primary'>Submit</button>
        </form>
    </div>
  </main>
{% endblock content %}

templates/scripts.html
{% load static %}
<!-- SCRIPTS -->
<!-- JQuery -->
<script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
<!-- Bootstrap tooltips -->
<script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
<!-- Initializations -->
<script type="text/javascript">
  // Animations initialization
  new WOW().init();

</script>

templates/stripe_payment_form.html
{% extends 'base.html' %}
{% block title %} Payment | {{ block.super }} {% endblock title %} 

{% block extra_head %}
<style type='text/css'>
/**
 * The CSS shown here will not be introduced in the Quickstart guide, but shows
 * how you can use CSS to style your Element's container.
 */
.StripeElement {
  box-sizing: border-box;

  height: 40px;

  padding: 10px 12px;

  border: 1px solid transparent;
  border-radius: 4px;
  background-color: white;

  box-shadow: 0 1px 3px 0 #e6ebf1;
  -webkit-transition: box-shadow 150ms ease;
  transition: box-shadow 150ms ease;
}

.StripeElement--focus {
  box-shadow: 0 1px 3px 0 #cfd7df;
}

.StripeElement--invalid {
  border-color: #fa755a;
}

.StripeElement--webkit-autofill {
  background-color: #fefde5 !important;
}
</style>
{% endblock extra_head %}

{% block content %}
<form action="." method="post" id="payment-form">
{% csrf_token %}
  <div class="form-row">
    <label for="card-element">
      Credit or debit card
    </label>
    <div id="card-element">
      <!-- A Stripe Element will be inserted here. -->
    </div>

    <!-- Used to display form errors. -->
    <div id="card-errors" role="alert"></div>
  </div>

  <button>Submit Payment</button>
</form>
{% endblock content %}

{% block extra_scripts %}
<script src="https://js.stripe.com/v3/"></script>
<script>
    // Create a Stripe client.
    var stripe = Stripe('{{STRIPE_PUBLIC_KEY}}');

    // Create an instance of Elements.
    var elements = stripe.elements();

    // Custom styling can be passed to options when creating an Element.
    // (Note that this demo uses a wider set of styles than the guide below.)
    var style = {
    base: {
        color: '#32325d',
        fontFamily: '"Helvetica Neue", Helvetica, sans-serif',
        fontSmoothing: 'antialiased',
        fontSize: '16px',
        '::placeholder': {
        color: '#aab7c4'
        }
    },
    invalid: {
        color: '#fa755a',
        iconColor: '#fa755a'
    }
    };

    // Create an instance of the card Element.
    var card = elements.create('card', {style: style});

    // Add an instance of the card Element into the `card-element` <div>.
    card.mount('#card-element');
    // Handle real-time validation errors from the card Element.
    card.on('change', function(event) {
    var displayError = document.getElementById('card-errors');
    if (event.error) {
        displayError.textContent = event.error.message;
    } else {
        displayError.textContent = '';
    }
    });

    // Handle form submission.
    var form = document.getElementById('payment-form');
    form.addEventListener('submit', function(event) {
    event.preventDefault();

    stripe.createToken(card).then(function(result) {
        if (result.error) {
        // Inform the user if there was an error.
        var errorElement = document.getElementById('card-errors');
        errorElement.textContent = result.error.message;
        } else {
        // Send the token to your server.
        stripeTokenHandler(result.token);
        }
    });
    });

    // Submit the form with the token ID.
    function stripeTokenHandler(token) {
    // Insert the token ID into the form so it gets submitted to the server
    var form = document.getElementById('payment-form');
    var hiddenInput = document.createElement('input');
    hiddenInput.setAttribute('type', 'hidden');
    hiddenInput.setAttribute('name', 'stripeToken');
    hiddenInput.setAttribute('value', token.id);
    form.appendChild(hiddenInput);

    // Submit the form
    form.submit();
    }
</script>
{% endblock extra_scripts %}